[theme]
base = "dark"
primaryColor = "#00ff88"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#00ff88"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false 